#include "exit.h"

/* 
  外部控制退出循环 (Generated by Claude)
  函数：signal_handler, check_keep_file
*/
volatile sig_atomic_t keep_running = 1;

void signal_handler(int signum) {
    if (signum == SIGINT || signum == SIGTERM) {
        log_info("Received signal to terminate: %d", signum);
        keep_running = 0;
    }
}

int check_keep_file() {
    if (access(KEEP_FILE, F_OK) != 0) {
        //remove(KEEP_FILE);
        log_info("Keep file removed...");
        keep_running = 0;
        return 1;
    }
    return 0;
}